exclude: ^(docs/logos|pymc/tests/data)/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: requirements-txt-fixer
        exclude: ^requirements-dev\.txt$
    -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
    - id: mypy
      name: Run static type checks
      language: python
      entry: python ./scripts/run_mypy.py --verbose
      additional_dependencies:
      - pandas
      - types-cachetools
      - types-filelock
      - types-setuptools
      - arviz
      - aesara==2.6.2
      - aeppl==0.0.28
      always_run: true
      require_serial: true
      pass_filenames: false
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/pylint
  rev: v2.13.5
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^pymc/
- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.3.0
  hooks:
    - id: no-print-statements
      files: ^pymc/
    - id: conda-env-sorter
      files: ^conda-envs/environment-dev-py.+\.yml$
- repo: local
  hooks:
    - id: check-no-tests-are-ignored
      additional_dependencies: [pandas,pyyaml]
      entry: python scripts/check_all_tests_are_covered.py
      files: ^\.github/workflows/pytest\.yml$
      language: python
      name: Check no tests are ignored
      pass_filenames: false
    - id: pip-from-conda
      additional_dependencies: [pyyaml]
      entry: python scripts/generate_pip_deps_from_conda.py
      files: ^conda-envs/environment-dev-py.+.yml$
      language: python
      name: Generate pip dependency from conda
    - id: no-relative-imports
      name: No relative imports
      entry: from \.[\.\w]* import
      types: [python]
      language: pygrep
    - id: no-internal-links
      name: Check no internal links are in the docs
      description: >-
        'A quick check for the links in the intersphinx '
        'mapping inside `docs/source/`'
        'See docs/source/conf.py for more information.'
      files: ^docs/source/
      # Files that should be ignored:
      # - index.md
      # - 404.md
      # - contributing/release_checklist.md
      # The other files are under development and should be
      # removed from the list once they are revised.
      exclude: >
          (?x)(index.md|
               404.md|
               contributing/release_checklist.md|
               contributing/developer_guide.rst|
               learn/examples.md)
      entry: >
          (?x)(arviz-devs.github.io|
               aesara.readthedocs.io|
               aeppl.readthedocs.io|
               pymc-experimental.readthedocs.io|
               docs.pymc.io|
               numpy.org/doc|
               pymc-examples.readthedocs.io|
               myst-parser.readthedocs.io|
               myst-nb.readthedocs.io|
               docs.python.org|
               xarray.pydata.org)
      language: pygrep
      types_or: [markdown, rst, jupyter]
