version: 2

sphinx:
    configuration: docs/source/conf.py

python:
   install:
   - method: pip
     path: .

conda:
  environment: "conda-envs/environment-dev.yml"

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
