name: pymc-dev-py37
channels:
- conda-forge
- defaults
dependencies:
- aesara>=2.1.0
- arviz>=0.11.2
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- ipython>=7.16
- libblas=*=*mkl
- mkl-service
- myst-nb
- numpy=1.15
- numpydoc>=0.9
- pandas=0.24
- pre-commit>=2.8.0
- pydata-sphinx-theme
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.7
- recommonmark>=0.4
- scipy>1.4.1
- sphinx-autobuild>=0.7
- sphinx-panels
- sphinx>=1.5
- typing-extensions
- watermark
