# "dev" conda envs are to be used by devs in setting their local environments
name: pymc-dev-py37
channels:
- conda-forge
- defaults
dependencies:
- aeppl=0.0.26
- aesara=2.4.0
- arviz>=0.11.4
- blas
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- ipython>=7.16
- myst-nb
- numpy>=1.15.0
- numpydoc<1.2
- pandas>=0.24.0
- pip
- pre-commit>=2.8.0
- pydata-sphinx-theme
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.7
- scipy>=1.4.1
- sphinx-copybutton
- sphinx-notfound-page
- sphinx>=1.5
- typing-extensions>=3.7.4
- watermark
- pip:
  - polyagamma
  - sphinx-design
  - sphinx-remove-toctrees
