# "dev" conda envs are to be used by devs in setting their local environments
name: pymc-dev
channels:
- conda-forge
- defaults
dependencies:
# Base dependencies
- aeppl=0.0.36
- aesara=2.8.6
- arviz>=0.12.0
- blas
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- numpy>=1.15.0
- pandas>=0.24.0
- pip
- python-graphviz
- networkx
- scipy>=1.4.1
- typing-extensions>=3.7.4
# Extra dependencies for dev, testing and docs build
- ipython>=7.16
- jax
- jupyter-sphinx
- myst-nb
- numpydoc
- pre-commit>=2.8.0
- pydata-sphinx-theme<0.10.1
- pytest-cov>=2.5
- pytest>=3.0
- sphinx-copybutton
- sphinx-design
- sphinx-notfound-page
- sphinx>=1.5
- sphinxext-rediraffe
- watermark
- polyagamma
- sphinx-remove-toctrees
