# "test" conda envs are used to set up our CI environment in GitHub actions
name: pymc-test-py39
channels:
- conda-forge
- defaults
dependencies:
- aeppl=0.0.26
- aesara=2.4.0
- arviz>=0.11.4
- blas
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- ipython>=7.16
- libblas=*=*mkl
- mkl-service
- numpy>=1.15.0
- pandas>=0.24.0
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.9
- scipy>=1.4.1
- typing-extensions>=3.7.4
