name: pymc-dev-py38
channels:
- conda-forge
- defaults
dependencies:
 # base dependencies (see install guide for Windows)
- aeppl=0.0.27
- aesara=2.5.1
- arviz>=0.12.0
- blas
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- numpy>=1.15.0
- pandas>=0.24.0
- pip
- python=3.8
- python-graphviz
- scipy>=1.4.1
- typing-extensions>=3.7.4
# Extra stuff for dev, testing and docs build
- ipython>=7.16
- myst-nb
- numpydoc<1.2
- pre-commit>=2.8.0
- pydata-sphinx-theme
- pytest-cov>=2.5
- pytest>=3.0
- sphinx-autobuild>=0.7
- sphinx-copybutton
- sphinx-notfound-page
- sphinx>=1.5
- watermark
- pip:
  - sphinx-design
  - sphinx-remove-toctrees
