name: nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-publish-nightly:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install build
      - name: Build the sdist
        run: python -m build --sdist .
        env:
          BUILD_PYMC_NIGHTLY: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN_PYMC_NIGHTLY }}
  test-install-job:
    needs: build-and-publish-nightly
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Give PyPI a chance to update the index
      run: sleep 240
    - name: Install from PyPI
      run: |
        pip install pymc-nightly==${GITHUB_REF:11}.dev$(date +"%Y%m%d")
