name: tests

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "pymc/**.py"
      - "*.py"
      - "conda-envs/**"
      - "codecov.yml"
      - "scripts/*.sh"
  push:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
      - "pymc/**.py"
      - "*.py"
      - "conda-envs/**"
      - "codecov.yml"
      - "scripts/*.sh"

# Tests are split into multiple jobs to accelerate the CI.
# Different jobs should be organized to take approximately the same
# time to complete (and not be prohibitely slow).
# Because GitHub Actions don't support YAML anchors, we have to place the
# splitting of testfiles into groups in the strategy/matrix/test-subset
# and can't re-use the groups across jobs.
# A pre-commit hook (scripts/check_all_tests_are_covered.py)
# enforces that test run just once per OS / floatX setting.

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        floatx: [float64]
        test-subset:
          - |
            pymc/tests/test_util.py
            pymc/tests/test_logprob.py
            pymc/tests/test_aesaraf.py
            pymc/tests/test_math.py
            pymc/tests/test_posdef_sym.py
            pymc/tests/test_ndarray_backend.py
            pymc/tests/test_hmc.py
            pymc/tests/test_func_utils.py
            pymc/tests/test_shape_handling.py
            pymc/tests/test_starting.py
            pymc/tests/test_mixture.py

          - |
            pymc/tests/test_distributions.py

          - |
            pymc/tests/test_tuning.py
            pymc/tests/test_shared.py
            pymc/tests/test_types.py
            pymc/tests/test_distributions_moments.py

          - |
            pymc/tests/test_modelcontext.py
            pymc/tests/test_dist_math.py
            pymc/tests/test_minibatches.py
            pymc/tests/test_pickling.py
            pymc/tests/test_transforms.py
            pymc/tests/test_parallel_sampling.py

          - |
            pymc/tests/test_distributions_random.py
            pymc/tests/test_distributions_timeseries.py
            pymc/tests/test_gp.py
            pymc/tests/test_model.py
            pymc/tests/test_model_graph.py
            pymc/tests/test_ode.py
            pymc/tests/test_profile.py
            pymc/tests/test_quadpotential.py

      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test-py37.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test-py37.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test-py37
          channel-priority: strict
          environment-file: conda-envs/environment-test-py37.yml
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test-py37
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        run: |
          conda activate pymc-test-py37
          python -m pytest -vv --cov=pymc --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  windows:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float64]
        test-subset:
          - pymc/tests/test_variational_inference.py pymc/tests/test_initial_point.py
          - pymc/tests/test_pickling.py pymc/tests/test_profile.py pymc/tests/test_step.py
          - pymc/tests/test_gp.py pymc/tests/test_ode.py pymc/tests/test_smc.py pymc/tests/test_parallel_sampling.py
          - pymc/tests/test_sampling.py pymc/tests/test_posteriors.py

      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=core2'
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-envs/environment-test-py38.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/windows-environment-test-py38.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test-py38
          channel-priority: strict
          environment-file: conda-envs/windows-environment-test-py38.yml
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test-py38
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        # This job uses a cmd shell, therefore the environment variable syntax is different!
        # The ">-" in the next line replaces newlines with spaces (see https://stackoverflow.com/a/66809682).
        run: >-
          conda activate pymc-test-py38 &&
          python -m pytest -vv --cov=pymc --cov-report=xml --cov-report term --durations=50 %TEST_SUBSET%
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  macos:
    strategy:
      matrix:
        os: [macos-latest]
        floatx: [float64]
        test-subset:
          - |
            pymc/tests/test_parallel_sampling.py
            pymc/tests/test_data_container.py
            pymc/tests/test_missing.py

          - |
            pymc/tests/test_sampling.py

          - |
            pymc/tests/test_idata_conversion.py
            pymc/tests/test_updates.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test-py39.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test-py39.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test-py39
          channel-priority: strict
          environment-file: conda-envs/environment-test-py39.yml
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pymc
        run: |
          conda activate pymc-test-py39
          pip install -e .
          python --version
      - name: Run tests
        run: |
          python -m pytest -vv --cov=pymc --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  jax:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        floatx: [float64]
        test-subset:
          - pymc/tests/test_sampling_jax.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test-py39.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test-py39.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test-py39
          channel-priority: strict
          environment-file: conda-envs/environment-test-py39.yml
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pymc
        run: |
          conda activate pymc-test-py39
          pip install -e .
          python --version
      - name: Install jax specific dependencies
        run: |
          conda activate pymc-test-py39
          pip install "numpyro>=0.8.0"
          pip install git+https://github.com/blackjax-devs/blackjax.git@main
      - name: Run tests
        run: |
          python -m pytest -vv --cov=pymc --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: TEST_SUBSET
          name: JAX tests - ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  float32:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float32]
        test-subset:
        - pymc/tests/test_sampling.py pymc/tests/test_ode.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=core2'
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-envs/environment-test-py38.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/windows-environment-test-py38.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test-py38
          channel-priority: strict
          environment-file: conda-envs/windows-environment-test-py38.yml
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test-py38
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        # This job uses a cmd shell, therefore the environment variable syntax is different!
        # The ">-" in the next line replaces newlines with spaces (see https://stackoverflow.com/a/66809682).
        run: >-
          conda activate pymc-test-py38 &&
          python -m pytest -vv --cov=pymc --cov-report=xml --cov-report term --durations=50 %TEST_SUBSET%
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
